micronaut:
  application:
    name: desafio_pix_rest
  server:
    ssl:
      port: 8080


grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      for-address: '${KEY_MANAGER_HOST}:localhost${KEY_MANAGER_PORT:50051}'